project:
  type: book

book:
  title: "Introduction to Data Science"
  subtitle: "STAT 3255/5255 @ UConn, Fall 2024"
  author:
    - name: "Jun Yan and Students in Fall 2024:"
    - name: Jack Bienveune
    - name: Zachary Blanchard
    - name: Sara Clokey
    - name: Thea Johnson
    - name: Rahul Manna
    - name: Julia Mazzola
    - name: Deyu Xu
  date: today

  sidebar:
    logo: images/ids-f24.png
  
  chapters:
    - index.qmd
    - intro.qmd
    - git.qmd
    - quarto.qmd
    - python.qmd
    - communication.qmd
    - manipulation.qmd
    - visualization.qmd
    - stats.qmd
    - machinelearning.qmd
    - supervised.qmd
    - unsupervised.qmd
    - reinforcement.qmd
    - advanced.qmd
    - exercises.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    include-in-header: preamble.tex


execute:
  freeze: auto
