project:
  type: book

book:
  title: "Introduction to Data Science"
  subtitle: "STAT 3255/5255 @ UConn, Fall 2024"
  author:
    - name: "Jun Yan and Students in Fall 2024:"
    - name: Zachary Blanchard, Sara Clokey
    - name: Julia Mazzola, Jack Bienvenue
  date: today

  sidebar:
    logo: images/ids-f24.png
  
  chapters:
    - index.qmd
    - intro.qmd
    - git.qmd
    - quarto.qmd
    - python.qmd
    - communication.qmd
    - manipulation.qmd
    - visualization.qmd
    - stats.qmd
    - supervised.qmd
    - spatial_data_visualization.qmd
    - exercises.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook

execute:
  freeze: auto
